namespace EFTHelper.Enums
{
    public enum ItemTypes
    {
        Any,
        Ammo,
        AmmoBox,
        Armor,
        Backpack,
        Barter,
        Container,
        Disabled,
        Glasses,
        Grenade,
        Gun,
        Headphones,
        Helmet,
        Keys,
        MarkedOnly,
        Mods,
        NoFlea,
        PistolGrip,
        Preset,
        Provisions,
        Rig,
        Suppressor,
        UnLootable,
        Wearable
    }
}
